#!/usr/bin/env bash

# enable all sysrq functions
echo 1 > /proc/sys/kernel/sysrq

# map eject key to SysRq
echo "786616 99" | keyfuzz -s -d /dev/input/by-id/usb-Apple_Inc._Apple_Internal_Keyboard___Trackpad-event-kbd
