#!/bin/bash

build() {
    add_runscript
}

help() {
    cat <<HELPEOF
This hook resets the SATA bus repeatedly until it initializes at its
full 3.0 Gbps speed.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
